apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.webserver.containerPort }}
      targetPort: {{ .Values.webserver.containerPort }}
  selector:
    app: airflow-webserver