images:
  airflow:
    repository: ghcr.io/nailus/airflow-executor
    tag: latest
    pullPolicy: IfNotPresent

webserver:
  replicas: 1
  containerPort: 8080
  command: ["airflow"]
  args: ["api-server"]
  env:
    - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
      value: "postgresql+psycopg2://airflow:password@database-postgresql:5432/airflow"

scheduler:
  replicas: 1

worker:
  replicas: 1

ingress:
  enabled: true
  host: airflow.local